/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as galleryTokenRouteRouteImport } from './routes/(gallery)/$token/route'
import { Route as galleryTokenIndexRouteImport } from './routes/(gallery)/$token/index'
import { Route as galleryTokenEventsEventIdRouteImport } from './routes/(gallery)/$token/events.$eventId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const galleryTokenRouteRoute = galleryTokenRouteRouteImport.update({
  id: '/(gallery)/$token',
  path: '/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const galleryTokenIndexRoute = galleryTokenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => galleryTokenRouteRoute,
} as any)
const galleryTokenEventsEventIdRoute =
  galleryTokenEventsEventIdRouteImport.update({
    id: '/events/$eventId',
    path: '/events/$eventId',
    getParentRoute: () => galleryTokenRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$token': typeof galleryTokenRouteRouteWithChildren
  '/$token/': typeof galleryTokenIndexRoute
  '/$token/events/$eventId': typeof galleryTokenEventsEventIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$token': typeof galleryTokenIndexRoute
  '/$token/events/$eventId': typeof galleryTokenEventsEventIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(gallery)/$token': typeof galleryTokenRouteRouteWithChildren
  '/(gallery)/$token/': typeof galleryTokenIndexRoute
  '/(gallery)/$token/events/$eventId': typeof galleryTokenEventsEventIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$token' | '/$token/' | '/$token/events/$eventId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$token' | '/$token/events/$eventId'
  id:
    | '__root__'
    | '/'
    | '/(gallery)/$token'
    | '/(gallery)/$token/'
    | '/(gallery)/$token/events/$eventId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  galleryTokenRouteRoute: typeof galleryTokenRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(gallery)/$token': {
      id: '/(gallery)/$token'
      path: '/$token'
      fullPath: '/$token'
      preLoaderRoute: typeof galleryTokenRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(gallery)/$token/': {
      id: '/(gallery)/$token/'
      path: '/'
      fullPath: '/$token/'
      preLoaderRoute: typeof galleryTokenIndexRouteImport
      parentRoute: typeof galleryTokenRouteRoute
    }
    '/(gallery)/$token/events/$eventId': {
      id: '/(gallery)/$token/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/$token/events/$eventId'
      preLoaderRoute: typeof galleryTokenEventsEventIdRouteImport
      parentRoute: typeof galleryTokenRouteRoute
    }
  }
}

interface galleryTokenRouteRouteChildren {
  galleryTokenIndexRoute: typeof galleryTokenIndexRoute
  galleryTokenEventsEventIdRoute: typeof galleryTokenEventsEventIdRoute
}

const galleryTokenRouteRouteChildren: galleryTokenRouteRouteChildren = {
  galleryTokenIndexRoute: galleryTokenIndexRoute,
  galleryTokenEventsEventIdRoute: galleryTokenEventsEventIdRoute,
}

const galleryTokenRouteRouteWithChildren =
  galleryTokenRouteRoute._addFileChildren(galleryTokenRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  galleryTokenRouteRoute: galleryTokenRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
