/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminAuthedRouteRouteImport } from './routes/admin/_authed/route'
import { Route as galleryTokenRouteRouteImport } from './routes/(gallery)/$token/route'
import { Route as AdminAuthedIndexRouteImport } from './routes/admin/_authed/index'
import { Route as galleryTokenIndexRouteImport } from './routes/(gallery)/$token/index'
import { Route as AdminAuthedGalleriesIdRouteImport } from './routes/admin/_authed/galleries/$id'
import { Route as galleryTokenEventsEventIdRouteImport } from './routes/(gallery)/$token/events.$eventId'
import { Route as AdminAuthedGalleriesIdIndexRouteImport } from './routes/admin/_authed/galleries/$id.index'
import { Route as AdminAuthedGalleriesIdEventsEventIdRouteImport } from './routes/admin/_authed/galleries/$id.events.$eventId'

const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAuthedRouteRoute = AdminAuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => AdminRouteRoute,
} as any)
const galleryTokenRouteRoute = galleryTokenRouteRouteImport.update({
  id: '/(gallery)/$token',
  path: '/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthedIndexRoute = AdminAuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAuthedRouteRoute,
} as any)
const galleryTokenIndexRoute = galleryTokenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => galleryTokenRouteRoute,
} as any)
const AdminAuthedGalleriesIdRoute = AdminAuthedGalleriesIdRouteImport.update({
  id: '/galleries/$id',
  path: '/galleries/$id',
  getParentRoute: () => AdminAuthedRouteRoute,
} as any)
const galleryTokenEventsEventIdRoute =
  galleryTokenEventsEventIdRouteImport.update({
    id: '/events/$eventId',
    path: '/events/$eventId',
    getParentRoute: () => galleryTokenRouteRoute,
  } as any)
const AdminAuthedGalleriesIdIndexRoute =
  AdminAuthedGalleriesIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminAuthedGalleriesIdRoute,
  } as any)
const AdminAuthedGalleriesIdEventsEventIdRoute =
  AdminAuthedGalleriesIdEventsEventIdRouteImport.update({
    id: '/events/$eventId',
    path: '/events/$eventId',
    getParentRoute: () => AdminAuthedGalleriesIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/$token': typeof galleryTokenRouteRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/$token/': typeof galleryTokenIndexRoute
  '/admin/': typeof AdminAuthedIndexRoute
  '/$token/events/$eventId': typeof galleryTokenEventsEventIdRoute
  '/admin/galleries/$id': typeof AdminAuthedGalleriesIdRouteWithChildren
  '/admin/galleries/$id/': typeof AdminAuthedGalleriesIdIndexRoute
  '/admin/galleries/$id/events/$eventId': typeof AdminAuthedGalleriesIdEventsEventIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminAuthedIndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/$token': typeof galleryTokenIndexRoute
  '/$token/events/$eventId': typeof galleryTokenEventsEventIdRoute
  '/admin/galleries/$id': typeof AdminAuthedGalleriesIdIndexRoute
  '/admin/galleries/$id/events/$eventId': typeof AdminAuthedGalleriesIdEventsEventIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/(gallery)/$token': typeof galleryTokenRouteRouteWithChildren
  '/admin/_authed': typeof AdminAuthedRouteRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/(gallery)/$token/': typeof galleryTokenIndexRoute
  '/admin/_authed/': typeof AdminAuthedIndexRoute
  '/(gallery)/$token/events/$eventId': typeof galleryTokenEventsEventIdRoute
  '/admin/_authed/galleries/$id': typeof AdminAuthedGalleriesIdRouteWithChildren
  '/admin/_authed/galleries/$id/': typeof AdminAuthedGalleriesIdIndexRoute
  '/admin/_authed/galleries/$id/events/$eventId': typeof AdminAuthedGalleriesIdEventsEventIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/$token'
    | '/admin/login'
    | '/$token/'
    | '/admin/'
    | '/$token/events/$eventId'
    | '/admin/galleries/$id'
    | '/admin/galleries/$id/'
    | '/admin/galleries/$id/events/$eventId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin/login'
    | '/$token'
    | '/$token/events/$eventId'
    | '/admin/galleries/$id'
    | '/admin/galleries/$id/events/$eventId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/(gallery)/$token'
    | '/admin/_authed'
    | '/admin/login'
    | '/(gallery)/$token/'
    | '/admin/_authed/'
    | '/(gallery)/$token/events/$eventId'
    | '/admin/_authed/galleries/$id'
    | '/admin/_authed/galleries/$id/'
    | '/admin/_authed/galleries/$id/events/$eventId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  galleryTokenRouteRoute: typeof galleryTokenRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/_authed': {
      id: '/admin/_authed'
      path: ''
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAuthedRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/(gallery)/$token': {
      id: '/(gallery)/$token'
      path: '/$token'
      fullPath: '/$token'
      preLoaderRoute: typeof galleryTokenRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_authed/': {
      id: '/admin/_authed/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAuthedIndexRouteImport
      parentRoute: typeof AdminAuthedRouteRoute
    }
    '/(gallery)/$token/': {
      id: '/(gallery)/$token/'
      path: '/'
      fullPath: '/$token/'
      preLoaderRoute: typeof galleryTokenIndexRouteImport
      parentRoute: typeof galleryTokenRouteRoute
    }
    '/admin/_authed/galleries/$id': {
      id: '/admin/_authed/galleries/$id'
      path: '/galleries/$id'
      fullPath: '/admin/galleries/$id'
      preLoaderRoute: typeof AdminAuthedGalleriesIdRouteImport
      parentRoute: typeof AdminAuthedRouteRoute
    }
    '/(gallery)/$token/events/$eventId': {
      id: '/(gallery)/$token/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/$token/events/$eventId'
      preLoaderRoute: typeof galleryTokenEventsEventIdRouteImport
      parentRoute: typeof galleryTokenRouteRoute
    }
    '/admin/_authed/galleries/$id/': {
      id: '/admin/_authed/galleries/$id/'
      path: '/'
      fullPath: '/admin/galleries/$id/'
      preLoaderRoute: typeof AdminAuthedGalleriesIdIndexRouteImport
      parentRoute: typeof AdminAuthedGalleriesIdRoute
    }
    '/admin/_authed/galleries/$id/events/$eventId': {
      id: '/admin/_authed/galleries/$id/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/admin/galleries/$id/events/$eventId'
      preLoaderRoute: typeof AdminAuthedGalleriesIdEventsEventIdRouteImport
      parentRoute: typeof AdminAuthedGalleriesIdRoute
    }
  }
}

interface AdminAuthedGalleriesIdRouteChildren {
  AdminAuthedGalleriesIdIndexRoute: typeof AdminAuthedGalleriesIdIndexRoute
  AdminAuthedGalleriesIdEventsEventIdRoute: typeof AdminAuthedGalleriesIdEventsEventIdRoute
}

const AdminAuthedGalleriesIdRouteChildren: AdminAuthedGalleriesIdRouteChildren =
  {
    AdminAuthedGalleriesIdIndexRoute: AdminAuthedGalleriesIdIndexRoute,
    AdminAuthedGalleriesIdEventsEventIdRoute:
      AdminAuthedGalleriesIdEventsEventIdRoute,
  }

const AdminAuthedGalleriesIdRouteWithChildren =
  AdminAuthedGalleriesIdRoute._addFileChildren(
    AdminAuthedGalleriesIdRouteChildren,
  )

interface AdminAuthedRouteRouteChildren {
  AdminAuthedIndexRoute: typeof AdminAuthedIndexRoute
  AdminAuthedGalleriesIdRoute: typeof AdminAuthedGalleriesIdRouteWithChildren
}

const AdminAuthedRouteRouteChildren: AdminAuthedRouteRouteChildren = {
  AdminAuthedIndexRoute: AdminAuthedIndexRoute,
  AdminAuthedGalleriesIdRoute: AdminAuthedGalleriesIdRouteWithChildren,
}

const AdminAuthedRouteRouteWithChildren =
  AdminAuthedRouteRoute._addFileChildren(AdminAuthedRouteRouteChildren)

interface AdminRouteRouteChildren {
  AdminAuthedRouteRoute: typeof AdminAuthedRouteRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAuthedRouteRoute: AdminAuthedRouteRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface galleryTokenRouteRouteChildren {
  galleryTokenIndexRoute: typeof galleryTokenIndexRoute
  galleryTokenEventsEventIdRoute: typeof galleryTokenEventsEventIdRoute
}

const galleryTokenRouteRouteChildren: galleryTokenRouteRouteChildren = {
  galleryTokenIndexRoute: galleryTokenIndexRoute,
  galleryTokenEventsEventIdRoute: galleryTokenEventsEventIdRoute,
}

const galleryTokenRouteRouteWithChildren =
  galleryTokenRouteRoute._addFileChildren(galleryTokenRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  galleryTokenRouteRoute: galleryTokenRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
